spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 612001
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8009
  servlet:
    context-path: /bmft