##网易系(126/163/yeah)邮箱配置
spring:
  mail:
    host: smtp.163.com #发送邮件服务器
    username: xx@126.com #发送邮件的邮箱地址
    password: xxxxxxx #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    #注意这里的警告并没有错 ，你加上的空格就会报错。
    from: xxx@126.com # 发送邮件的地址，和上面username一致,
    # 可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  profiles: wangyi